# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3451ccf369ed388e45abdf99e4298054"
name = "parcelsBaltic"
handle = "parcelsbaltic"
application_url = "https://graduation-farmers-batch-belongs.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_markets,read_shipping,write_shipping"

[auth]
redirect_urls = ["https://graduation-farmers-batch-belongs.trycloudflare.com/auth/callback", "https://graduation-farmers-batch-belongs.trycloudflare.com/auth/shopify/callback", "https://graduation-farmers-batch-belongs.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
